### PR TITLE
change_1212

### PR DESCRIPTION
**Pull request by yotsuzuka**

### CODE REVIEW

**Comment by DmitryNeverov** [comment]
First of all, find a hidden file .authors and add yourself to the list

**Comment by yotsuzuka** [comment]
I changed .authors and did commit and push.
Did I success?

**Comment by DmitryNeverov** [comment]
Doesn't seem like you pushed those changes

**Comment by DmitryNeverov** [comment]
Now I see it

**Comment by yotsuzuka** [comment]
Sorry, I did mistake.
I fixed.

**Pull request merged**
